version: '3.4'

networks:
  mm:

services:
  magic_mirror:
    restart: always
    container_name: magic_mirror
    networks:
      - mm
    build: .
    image: jhnoor/docker-magicmirror
    ports:
      - '80:80'
    volumes:
      - './config:/opt/magic_mirror/config'
      - './modules:/opt/magic_mirror/modules'

